// STRINGSSSS

// var str = "Hello World";
// // var str = "yoooo"
// console.log(str.length);
// // var str = "Hello World";
// console.log(str.indexOf("W"));
// console.log(str.slice(6));
// console.log(str.replace("World", "Universe"));
// console.log(str.toUpperCase());
// console.log(str.toLowerCase());
// console.log(str1.concat(str2));

let real_name = "Suhani"
let name = "Tiwari"

console.log("Her first name is " +real_name +"and her last name is " + name )
console.log(`Her first name is ${real_name} and her last name is ${name}`);